### ISSUE TITLE
search string matching issue

### ISSUE THREAD

**Issue by rolfmobile99** [hzeller/stuff-org#1]
search for "led" and you'll notice that bin 968 is in the gallery view.
this is incorrect, because this part is not an LED.
instead it seems to match a word in the notes field which is the word "sealed".

why not match from the beginning of words only?

just a suggestion!

-rolf

**Comment by hzeller** [comment]
Words are actually scored by distance how far they are from the beginning - so if a word shows up in the middle of a larger word and does not start with it, it gets penalized.
So that particular item is scored very far at the bottom (and yeah, it is the last item in the list). The first items in the list are all LEDs, so this is working perfectly.

We can't just use beginning of words, as you often want to search for substrings or don't really know how it is written. The scoring makes sure to still sort the things at the top that are likely the most useful.
